export const santosNeighborhoods = [
    { name: 'Aparecida' },
    { name: 'Boqueirão' },
    { name: 'Campo Grande' },
    { name: 'Embaré' },
    { name: 'Gonzaga' },
    { name: 'José Menino' },
    { name: 'Macuco' },
    { name: 'Marapé' },
    { name: 'Monte Serrat' },
    { name: 'Morro Nova Cintra' },
    { name: 'Orquidário' },
    { name: 'Pompéia' },
    { name: 'Paquetá' },
    { name: 'Ponta da Praia' },
    { name: 'Vila Belmiro' },
    { name: 'Vila Mathias' },
    { name: 'Vila Nova' },
    { name: 'Vila São Jorge' },
    { name: 'Vila Cascatinha' },
    { name: 'Vila Haddad' },
    { name: 'Vila Matias' },
    { name: 'Vila Progresso' },
    { name: 'Vila Rica' },
    { name: 'Vila São Bento' },
    { name: 'Vila Valença' },
    { name: 'Vila Vitória' }
    // Adicione mais bairros conforme necessário
];
